spring:
  application:
    name: realtor-connect
    time-zone: UTC
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${spring.application.name}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
  logging:
    level:
      com.kotyk.realtorconnect: info
      org.springframework: info
      org.hibernate: info
      org.flywaydb: info

network:
  app-domain: ${APP_DOMAIN:http://localhost:8080}
  swagger-ui-url: ${network.app-domain}/swagger-ui/index.html
  verify-email-url: ${network.app-domain}/users/verifyEmail/
  defaultAvatarUrl: https://i.imgur.com/meePOPU.png

email:
  enabled: ${EMAIL_ENABLED:true}
  server:
    credentials:
      username: ${EMAIL_USERNAME}
      password: ${EMAIL_PASSWORD}
    network:
      host: smtp.gmail.com
      port: 587
    properties:
      mail.protocol: smtp
      mail.test-connection: true
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  debugMode:
    enabled: ${DEBUG_EMAIL_ENABLED:false}
    from: info@realtorconnect.com
    server:
      credentials:
        username: user
        password: user
      network:
        host: localhost
        port: 1025

user:
  timeToVerifyEmailInDays: 7
  scheduler:
    delete-unverified-users-cron: "* */2 * * * *" # every 2 hours

realtor:
  plan-configuration:
    free:
      maxPublicRealEstates: 10
    premium:
      maxPublicRealEstates: 25
  daysToNotifyExpiresPremium: [ 1, 7 ]
  scheduler:
    reset-plan-cron: "0 0 * * * *" # every day at 00:00 AM
    send-email-when-premium-expires-cron: "0 10 * * * *" # every day at 10 AM

real-estate:
  daysForExpireCalled: 14
  scheduler:
    check-called: 60000 # every minute

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: ALWAYS
    configprops:
      show-values: ALWAYS

openapi:
  title: Realtor Connect
  version: 0.1
  description: An application that helps realtors to more easily control their objects and find clients

security.jwt:
  token-ttl: 18000000 # 5 hours
  secret: ${JWT_SECRET}
