spring:
  application.name: realtor-connect
  jpa.properties.hibernate:
    hbm2ddl.auto: validate
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${spring.application.name}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
  logging:
    level:
      com.kotyk.realtorconnect: info
      org.springframework: info
      org.hibernate: info
      org.flywaydb: info

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: ALWAYS
    configprops:
      show-values: ALWAYS

openapi:
  title: Realtor Connect
  version: 1.0
  description: An application that helps realtors to more easily control their objects and find clients

security.jwt:
  token-ttl: 18000000 # 5h
  secret: 4E7DF100807D059CDB6AC078B795DA9A3908AA2EECC0211620A86E41B87FD8E7