spring:
  application.name: realtor-connect
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${spring.application.name}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
  logging:
    level:
      com.kotyk.realtorconnect: info
      org.springframework: info
      org.hibernate: info
      org.flywaydb: info

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: ALWAYS
    configprops:
      show-values: ALWAYS

openapi:
  title: Realtor Connect
  version: 0.1
  description: An application that helps realtors to more easily control their objects and find clients

security.jwt:
  token-ttl: 18000000 # 5h
  secret: ${JWT_SECRET}
