spring:
  application:
    name: realtor-connect
    time-zone: UTC
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${spring.application.name}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
  logging:
    level:
      com.kotyk.realtorconnect: info
      org.springframework: info
      org.hibernate: info
      org.flywaydb: info

network:
  app-domain: ${APP_DOMAIN:http://localhost:8080}
  swagger-ui-url: ${network.app-domain}/swagger-ui/index.html
  verify-email-url: ${network.swagger-ui-url}#/User%20Controller/verifyEmail

email:
  enabled: ${EMAIL_ENABLED:true}
  debug-mode:
    enabled: ${EMAIL_DEBUG_ENABLED:true}
    debug-email: makurohashami@gmail.com
  server:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    protocol: smtp
    test-connection: true
    smtp-auth: true
    smtp-starttls-enabled: true

realtor:
  plan-configuration:
    free:
      maxPublicRealEstates: 10
    premium:
      maxPublicRealEstates: 25
  scheduler:
    reset-plan-cron: "1 0 * * * *" # every day at 00:01 AM

real-estate:
  daysForExpireCalled: 14
  scheduler:
    check-called-cron: "0 */2 * * * *" # every 2 hours

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: ALWAYS
    configprops:
      show-values: ALWAYS

openapi:
  title: Realtor Connect
  version: 0.1
  description: An application that helps realtors to more easily control their objects and find clients

security.jwt:
  token-ttl: 18000000 # 5h
  secret: ${JWT_SECRET}
